# Generated by Django 2.2.5 on 2019-09-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rectangle',
            old_name='breaddth',
            new_name='breadth',
        ),
    ]
